"""Branded PDF table export for list-view CSV/PDF export endpoints.

Shares Keep Track's brand colours and footer style with
services/pdf_report_service.py (the AI-report PDF builder), but produces a
single-purpose "give me this table as a PDF" document — a header (logo +
instance name), a title (with a subtitle for any active filters/date
range), the data as a striped table, and a footer with who generated it and
when. Used by the /export/pdf endpoints on Invoices, Contributions, and
Reconciliation.
"""
from datetime import datetime
from functools import partial
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

PRIMARY = colors.HexColor("#2D6B9F")
ACCENT = colors.HexColor("#1D9E75")
TEXT_DARK = colors.HexColor("#2C2C2A")
TEXT_MUTED = colors.HexColor("#6B6B67")
BORDER = colors.HexColor("#E4E4E0")
ROW_ALT = colors.HexColor("#F7F7F5")

PAGE_MARGIN = 1.5 * cm
HEADER_HEIGHT = 1.6 * cm
FOOTER_HEIGHT = 1.2 * cm


def _build_styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "export_title", parent=base["Title"], fontSize=17, leading=21, textColor=PRIMARY,
            alignment=0, spaceAfter=2,
        ),
        "subtitle": ParagraphStyle(
            "export_subtitle", parent=base["Normal"], fontSize=10, leading=14, textColor=TEXT_MUTED,
            spaceAfter=12,
        ),
        "table_header": ParagraphStyle(
            "table_header", parent=base["Normal"], fontSize=8.5, leading=11,
            textColor=colors.white, fontName="Helvetica-Bold",
        ),
        "table_cell": ParagraphStyle(
            "table_cell", parent=base["Normal"], fontSize=8.5, leading=11, textColor=TEXT_DARK,
        ),
    }


def _draw_logo(canvas, x: float, y: float, size: float = 0.9 * cm) -> None:
    """A small hand-drawn version of the app's bar-chart + tick-badge mark.

    No logo image file exists anywhere in the repo — frontend/src/components
    /Logo.jsx is inline SVG — so this mirrors its three shapes directly with
    canvas primitives rather than adding a new static asset just for PDF
    headers.
    """
    s = size / 48
    canvas.setFillColor(PRIMARY)
    canvas.rect(x + 6 * s, y + 8 * s, 7 * s, 16 * s, stroke=0, fill=1)
    canvas.rect(x + 17 * s, y + 8 * s, 7 * s, 24 * s, stroke=0, fill=1)
    canvas.rect(x + 28 * s, y + 8 * s, 7 * s, 32 * s, stroke=0, fill=1)
    canvas.setFillColor(ACCENT)
    canvas.circle(x + 37 * s, y + 37 * s, 10 * s, stroke=0, fill=1)


def _header_footer(canvas, doc, site_name: str, generated_by_username: str, generated_at: datetime) -> None:
    canvas.saveState()
    page_width, page_height = doc.pagesize

    # Header: logo + instance name, with a rule beneath.
    _draw_logo(canvas, PAGE_MARGIN, page_height - PAGE_MARGIN - 0.75 * cm)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.setFillColor(TEXT_DARK)
    canvas.drawString(PAGE_MARGIN + 1.2 * cm, page_height - PAGE_MARGIN - 0.45 * cm, site_name)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(
        PAGE_MARGIN, page_height - PAGE_MARGIN - HEADER_HEIGHT,
        page_width - PAGE_MARGIN, page_height - PAGE_MARGIN - HEADER_HEIGHT,
    )

    # Footer: generated-by / generated-at, and a page number.
    canvas.setStrokeColor(BORDER)
    canvas.line(PAGE_MARGIN, 1.4 * cm, page_width - PAGE_MARGIN, 1.4 * cm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(PAGE_MARGIN, 1 * cm, f"Generated by {generated_by_username}")
    canvas.drawCentredString(page_width / 2, 1 * cm, f"Generated at {generated_at:%d %b %Y, %H:%M}")
    canvas.drawRightString(page_width - PAGE_MARGIN, 1 * cm, f"Page {doc.page}")
    canvas.restoreState()


def generate_table_export_pdf(
    *,
    title: str,
    subtitle: str | None,
    site_name: str,
    columns: list[str],
    rows: list[list[str]],
    generated_by_username: str,
    generated_at: datetime,
) -> bytes:
    """Render a branded table-export PDF and return its bytes."""
    styles = _build_styles()
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=PAGE_MARGIN,
        rightMargin=PAGE_MARGIN,
        topMargin=PAGE_MARGIN + HEADER_HEIGHT,
        bottomMargin=PAGE_MARGIN + FOOTER_HEIGHT,
        title=title,
    )

    story = [Paragraph(title, styles["title"])]
    if subtitle:
        story.append(Paragraph(subtitle, styles["subtitle"]))
    else:
        story.append(Spacer(1, 0.4 * cm))

    if rows:
        header_row = [Paragraph(c, styles["table_header"]) for c in columns]
        body_rows = [[Paragraph(str(cell) if cell is not None else "", styles["table_cell"]) for cell in row] for row in rows]
        table = Table([header_row, *body_rows], repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, ROW_ALT]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(table)
    else:
        story.append(Paragraph("No records match the current filters.", styles["subtitle"]))

    on_page = partial(
        _header_footer,
        site_name=site_name,
        generated_by_username=generated_by_username,
        generated_at=generated_at,
    )
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()
