"""create categories table

Revision ID: a3f7c9d2e1b4
Revises: fe8ecc268931
Create Date: 2026-08-04 15:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f7c9d2e1b4'
down_revision: Union[str, None] = 'fe8ecc268931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Default categories seeded on first run — see docs/features.md and
# docs/database-schema.md. Seeded here (migration time) rather than at
# backend startup since this data is fixed, not env-driven, and Alembic is
# the single place schema + baseline data are established together.
DEFAULT_CATEGORIES = [
    {"name": "Electricity", "colour": "#378ADD", "active": True},
    {"name": "Water", "colour": "#1D9E75", "active": True},
    {"name": "Broadband", "colour": "#9B59B6", "active": True},
    {"name": "HVAC", "colour": "#E67E22", "active": True},
    {"name": "Alarm", "colour": "#E74C3C", "active": True},
    {"name": "Supplies", "colour": "#F39C12", "active": True},
    {"name": "General Maintenance", "colour": "#95A5A6", "active": True},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    categories_table = op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('colour', sa.String(length=7), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

    op.bulk_insert(categories_table, DEFAULT_CATEGORIES)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
