"""create invoices table

Revision ID: c8d1a6b52e47
Revises: b7e2f4a91c33
Create Date: 2026-08-04 16:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d1a6b52e47'
down_revision: Union[str, None] = 'b7e2f4a91c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('signed_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('financial_year_id', sa.Integer(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duplicate_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id']),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id']),
    sa.ForeignKeyConstraint(['created_by'], ['users.id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_financial_year_id'), 'invoices', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_invoices_category_id'), 'invoices', ['category_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_category_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_financial_year_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
