"""create settings table

Revision ID: b7e4f9a1c3d8
Revises: d9f3c7e64a58
Create Date: 2026-08-04 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e4f9a1c3d8'
down_revision: Union[str, None] = 'd9f3c7e64a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Seeded default — signing is on unless an Admin turns it off. See
# docs/decisions-log.md and docs/features.md#8-settings.
DEFAULT_SETTINGS = [
    {"key": "signing_enabled", "value": "true"},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    settings_table = op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###

    op.bulk_insert(settings_table, DEFAULT_SETTINGS)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
