"""create contributions table

Revision ID: e1a2b3c4d5e6
Revises: b7e4f9a1c3d8
Create Date: 2026-08-04 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a2b3c4d5e6'
down_revision: Union[str, None] = 'b7e4f9a1c3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_contributions_month'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id']),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id']),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_contributions_fy_month', 'contributions', ['financial_year_id', 'month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contributions_fy_month', table_name='contributions')
    op.drop_table('contributions')
    # ### end Alembic commands ###
